### ISSUE TITLE
随便问问

### ISSUE THREAD

**Issue by leoxxx** [wrfree/free#10]
freefq.com这个站点不是你的吗？
https://github.com/freefq/free 这个REPO是你的吗？
不是的话就不回这条了。
是的话，那你之前第二个被BAN掉的回复我没看到。
另外建议你像这个REPO这么搞
https://github.com/anonymousbone/freefq
REPO只留README。连接都不要留，可以放在README里。

**Comment by wrfree** [comment]
看你写了这么多我再回一次。我只有bulink.xyz这一个网站，如果你在这个网站注册过也就不需要来问是不是这个问题了。

谢谢你的建议，我觉得直接黏贴链接很方便。
