### ISSUE TITLE
bulink.xyz无法重置密码

### ISSUE THREAD

**Issue by greenredstone** [wrfree/free#9]
无法收到重置邮件

**Comment by wrfree** [comment]
你这应该是号没了，最近删了很多没有认证邮箱的号。尤其是一些.xyz/.me/.cc结尾的邮箱账号都删了

**Comment by greenredstone** [comment]
> 你这应该是号没了，最近删了很多没有认证邮箱的号。尤其是一些.xyz/.me/.cc结尾的邮箱账号都删了

但我QQ邮箱现在还是收不到

**Comment by daviddongliu** [comment]
非常好的服务, 谢谢.
